name: login
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.8.0
  flutter_otp_text_field: ^1.2.0

  # fireBase Package
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  

  google_maps_flutter: ^2.9.0
  location: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter_native_splash:
#   color: "#F1A8BA"
#   color_dark: "#F1A8BA"
#   image: assets/logo/logo.png
#   image_dark: assets/logo/logo.png

#   android_12:
#     image: assets/logo/logo.png
#     icon_background_color: "#F1A8BA"
#     image_dark: assets/logo/logo.png
#     icon_background_color_dark: "#F1A8BA"


#F1A8BA

flutter:

  uses-material-design: true
  assets:
    - assets/images/my.jpg
    - assets/logo/logo.png 
    - assets/logo/fb.png
    - assets/logo/gogle.png
    - assets/images/welcome_img/wel1.png

  